server:
  port: 3000

spring:
  application:
    name: order-service
  data:
    mongodb:
      database: admin
      uri: mongodb://${SPRING_DATA_MONGODB_USERNAME}:${SPRING_DATA_MONGODB_PASSWORD}@${SPRING_DATA_MONGODB_HOST}:${SPRING_DATA_MONGODB_PORT}/${SPRING_DATA_MONGODB_DATABASE}?authSource=admin
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      start-saga: start-saga
      notify-ending: notify-ending
    consumer:
      group-id: order-service-group
      auto-offset-reset: latest